safe: false

lsi: false
# build settings
markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    span:
      line_numbers: false
    block:
      code_class: 'highlighter-rouge'
      css_class: 'highlighter-rouge'
      line_numbers: false
      start_line: 1

title: "Documentation"
description: "Documentation Projet"
static_files: "images"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Your website URL (e.g. http://example.github.io or http://www.example.com)
# Used for Sitemap.xml and your RSS feed
url: ""

# Enter your Google Analytics web tracking code (e.g. UA-000000000-0) to activate tracking
google_analytics: ""

# language settings
isolang: fr
isodir: ltr

verbose: true
collections:
  brand:
    permalink: /:collection/:name.html
    output: true
    weight: 0
  design:
    permalink: /:collection/:name.html
    output: true
    weight: 2
  styleguide:
    permalink: /:collection/:name.html
    output: true
    weight: 2
  docs:
    permalink: /:collection/:name.html
    output: true
    weight: 3
  # reports:
  #   permalink: /:collection/:name.html
  #   output: true
  #   weight: 3
  # templates:
  #   permalink: /:collection/:name.html
  #   output: true
  #   weight: 4
  # drupal:
  #   permalink: /:collection/:name.html
  #   output: true
  #   weight: 5
  # contribution:
  #   permalink: /:collection/:name.html
  #   output: true
  #   weight: 6

# exclude files
exclude:
  - LICENSE
  - README.md
  - CNAME
